services:
  api:
    build: .
    ports:
      - "3000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/productosdb
    depends_on:
      - mongo
  
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
